# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab6294643ca751de4702461ef5139c1ff4008b5548739756df7d3df0967591be0fd6b8f03878ea400ce16136ee51b2ea0c2956f018e7f91400f7f22d00b92de8

test:
  secret_key_base: aa5d88a20c4ae97d72dae9ca700e6df3733122c75e182fd2359cc05e88d8e0159f70a0ffbf913df510fbd23f57b469853164140014693a2123b4c45e5bca9512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
